name: Verify Gradle Data Capturing Samples

on: [ push, pull_request, workflow_dispatch ]

jobs:
  verification:
    name: Verification of ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'Dependency resolution'
            sample-file: 'capture-dependency-resolution/gradle-dependency-resolution.gradle'
          - name: 'Git diffs'
            sample-file: 'capture-git-diffs/gradle-git-diffs.gradle'
          - name: 'OS processes'
            sample-file: 'capture-os-processes/gradle-os-processes.gradle'
          - name: 'Quality checks'
            sample-file: 'capture-quality-check-issues/gradle-quality-check-issues.gradle'
          - name: 'Slow tasks'
            sample-file: 'capture-slow-workunit-executions/gradle-slow-task-executions.gradle'
          - name: 'Test task system properties'
            sample-file: 'capture-test-execution-system-properties/gradle-test-execution-system-properties.gradle'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Inject data capture script into Gradle build
        run: |
          # apply sample file
          echo "apply from: file(\"../build-data-capturing-gradle-samples/${{matrix.sample-file}}\")" >> common-gradle-enterprise-gradle-configuration/build.gradle
      - name: Run Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: tasks
          build-root-directory: 'common-gradle-enterprise-gradle-configuration'
