name: Verify Maven Build Caching Samples

on: [ push, pull_request, workflow_dispatch ]

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Node.js and Npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Yarn
        run: npm install -g yarn
      - name: Build with Maven
        working-directory: ./build-caching-maven-samples
        run: ./mvnw clean verify -Dgradle.scan.disabled=true
