name: Verify Maven Build Caching Samples

on: [ push, pull_request, workflow_dispatch ]

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Node.js and Npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Yarn
        run: npm install -g yarn
      - name: Build with Maven
        id: mvn-build
        working-directory: ./build-caching-maven-samples
        run: |
          ./mvnw -B clean verify -Dgradle.enterprise.url=https://ge.solutions-team.gradle.com -Dorg.slf4j.simpleLogger.log.gradle.goal.cache=debug 2>&1 | tee -a /tmp/gradle-build.log
          echo ::set-output name=hasUnknownParams::$(grep "Build caching was not enabled for this goal execution because the following parameters were not handled" /tmp/gradle-build.log | wc -l)    
      - name: Fail if unmapped mojo parameters
        run: exit 1
        if:  steps.mvn-build.outputs.hasUnknownParams != '0'