name: Validate Shell Scripts

on: [ push, pull_request, workflow_dispatch ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate
      uses: luizm/action-sh-checker@v0.1.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHELLCHECK_OPTS: -a -x
      with:
        sh_checker_comment: true
        sh_checker_exclude: "gradlew mvnw"
        sh_checker_shfmt_disable: true

